[build]
  base = "frontend"
  command = "npm install && REACT_APP_ENVIRONMENT=production npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_ENVIRONMENT = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
