[providers]
node = "18.x"

[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm install --production']

[phases.build]
cmds = ['echo "Node.js build completed successfully"']

[start]
cmd = 'npm start'
